In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df1 = pd.read_csv("records_final_series_test_final_bowlers_v6.csv")

In [3]:
df1.head()

Player    Country  Mat  Overs  Maidens  Runs  Wickets  Best  5w  \
0    Garrett T W  Australia    2   26.1       12    48        2  2|22   0   
1    Gregory D W  Australia    2    5.0        1     9        0   0|0   0   
2     Hodges J H  Australia    2   34.0        9    84        6   2|7   0   
3      Kendall T  Australia    2  140.3       56   215       14  7|55   1   
4  Midwinter W E  Australia    2  107.1       44   156        8  5|78   1   

   10w    Avg    S/R   E/R  Series_Code   H/A  Decade_Index  
0    0  24.00  52.50  2.74            1  Home             0  
1    0    NaN    NaN  2.70            1  Home             0  
2    0  14.00  22.67  3.71            1  Home             0  
3    0  15.36  40.21  2.29            1  Home             0  
4    0  19.50  53.63  2.18            1  Home             0

In [4]:
#df1.sort_values(['Series_Code', 'Mat'], ascending=[True, False], inplace=True)

In [5]:
#df1

In [6]:
series = df1['Decade_Index'].values
number, series_unique = np.unique(series, return_inverse = True)

In [7]:
players = df1['Player'].values
player_names, player_indices = np.unique(players, return_index = True)
player_dict_temp_3 = {}
for i in df1.index:
    if df1["Player"][i] in player_dict_temp_3.keys():
        player_dict_temp_3[df1["Player"][i]] = player_dict_temp_3[df1["Player"][i]] + [i]
    else:
        player_dict_temp_3[df1["Player"][i]] = [i]

In [8]:
series_codes = df1['Series_Code'].values
series_list, series_occurances, series_code = np.unique(series_codes, return_index=True, return_inverse = True)
series_code

array([  0,   0,   0, ..., 722, 722, 722], dtype=int64)

In [9]:
series_to_number = {'Australia':0, 'Pakistan':1, 'New Zealand':2, 'West Indies':3, 'England':4, 'India' :5, 'Sri Lanka':6, 'Bangladesh':7, 'Zimbabwe':8, 'South Africa':9} 
opposition_country =[]
series_country = []
j = 0
for i in series_occurances:
    home = 0
    away = 0
    j = i
    while 1 != 0:
        #print(j)
        if df1['H/A'][j] == 'Home' and home == 0:
            #print(df['Country'][j])
            series_country.append(series_to_number[df1['Country'][j]]) 
            home = home + 1
        elif df1['H/A'][j] == 'Away' and away == 0:    
            #print(df['Country'][j])
            opposition_country.append(series_to_number[df1['Country'][j]]) 
            away = away + 1
        elif home == 1 and away == 1:
            #print("hello")
            break
        j = j + 1 

In [10]:
series_country

[0,
 0,
 4,
 0,
 4,
 0,
 4,
 0,
 4,
 0,
 0,
 4,
 9,
 4,
 0,
 9,
 4,
 0,
 9,
 4,
 0,
 9,
 4,
 0,
 4,
 9,
 0,
 4,
 9,
 4,
 0,
 4,
 9,
 0,
 0,
 9,
 0,
 4,
 9,
 9,
 4,
 0,
 4,
 9,
 4,
 0,
 4,
 2,
 3,
 4,
 0,
 9,
 4,
 0,
 2,
 4,
 0,
 2,
 4,
 5,
 4,
 3,
 4,
 9,
 4,
 0,
 4,
 4,
 9,
 4,
 2,
 4,
 0,
 2,
 4,
 0,
 3,
 4,
 5,
 9,
 4,
 9,
 4,
 0,
 2,
 4,
 5,
 0,
 2,
 4,
 5,
 0,
 3,
 2,
 4,
 9,
 3,
 4,
 0,
 1,
 2,
 3,
 4,
 1,
 5,
 2,
 4,
 1,
 5,
 9,
 4,
 9,
 3,
 4,
 5,
 0,
 1,
 2,
 4,
 1,
 5,
 3,
 4,
 5,
 0,
 4,
 1,
 5,
 9,
 3,
 4,
 0,
 2,
 4,
 0,
 5,
 2,
 4,
 5,
 1,
 0,
 9,
 2,
 5,
 3,
 1,
 4,
 4,
 0,
 2,
 4,
 5,
 9,
 4,
 4,
 0,
 3,
 2,
 4,
 0,
 1,
 2,
 4,
 4,
 5,
 1,
 5,
 9,
 0,
 3,
 2,
 4,
 4,
 3,
 4,
 5,
 0,
 2,
 3,
 1,
 4,
 4,
 0,
 3,
 2,
 4,
 4,
 5,
 0,
 1,
 2,
 4,
 0,
 2,
 3,
 4,
 1,
 5,
 5,
 0,
 2,
 3,
 0,
 4,
 0,
 1,
 2,
 3,
 4,
 4,
 1,
 0,
 5,
 2,
 0,
 4,
 5,
 5,
 0,
 0,
 2,
 5,
 1,
 4,
 4,
 1,
 0,
 0,
 3,
 2,
 4,
 0,
 5,
 0,
 6,
 2,
 1,
 4,
 4,
 5,
 1,
 0,
 1,
 3,
 2,
 6,
 4,
 5,
 5,
 0,


In [11]:
len(series_country)

723

In [12]:
trps = np.zeros(723)
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        trps[series_code[i]] += df1["Runs"][i]

In [13]:
arpspc = np.zeros(10)
tmpc = np.zeros(10)
for i in range(len(trps)):
    tmpc[series_country[i]] += df1['Mat'][series_occurances[i]]
    arpspc[series_country[i]] += trps[i]

In [14]:
arpc=arpspc/tmpc

In [15]:
avr_average = np.average(arpc)

In [16]:
weights_arpc = np.average(arpc)/arpc

In [17]:
weights_arpc

array([0.90389964, 1.0380722 , 1.1192837 , 0.85252931, 0.95446444,
       0.96980682, 1.04872389, 1.03222664, 1.18738037, 0.97981671])

In [18]:
weighted_runs_arr = []
for i in df1.index:
    weighted_runs_arr.append(df1['Runs'][i]*weights_arpc[series_country[series_code[i]]])
weighted_runs_arr

[43.38718257177601,
 8.135096732208002,
 75.92756950060802,
 194.33842193608007,
 141.00834335827204,
 100.33285969723202,
 28.020888744272007,
 13.558494553680005,
 32.54038692883201,
 117.50695279856004,
 113.89135425091203,
 131.96934698915203,
 96.71726114958403,
 111.17965534017603,
 72.31197095296002,
 24.40529019662401,
 32.54038692883201,
 99.42896006032002,
 61.465175310016015,
 12.654594916768003,
 0.0,
 28.020888744272007,
 5.423397821472001,
 23.501390559712007,
 92.19776296502403,
 16.225895447617933,
 64.90358179047173,
 21.952682076188967,
 139.3518079618952,
 1.9089288761903451,
 60.13125959999587,
 125.0348413904676,
 65.8580462285669,
 105.94555262856416,
 87.81072830475587,
 10.499108819046898,
 21.952682076188967,
 144.12413015237107,
 31.63648729192001,
 122.02645098312003,
 180.77992738240005,
 232.30220668638407,
 331.7311667467041,
 48.81058039324802,
 27.11698910736001,
 13.558494553680005,
 245.86070124006406,
 471.83561046806415,
 115.69915352473603,
 55.1378

In [19]:
wtrps = np.zeros(723)
twps = np.zeros(723)
tops = np.zeros(723)
tbps = np.zeros(723)
balls = np.zeros(len(df1.index))
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        wtrps[series_code[i]] += weighted_runs_arr[i]
        twps[series_code[i]] += df1["Wickets"][i]
        balls[i] = math.floor(df1["Overs"][i])*6 + (df1["Overs"][i]- math.floor(df1["Overs"][i]))*10
        tbps[series_code[i]] += balls[i]
        
    tops[series_code[i]] += df1["Overs"][i]

In [20]:
bowl=np.zeros(len(df1.index))
for i in df1.index:
    bowl[i] = (wtrps[series_code[i]] - weighted_runs_arr[i])/(twps[series_code[i]]-df1["Wickets"][i])
    avg = df1["Avg"][i]
    bowl[i] = bowl[i]/avg
    if np.isnan(avg) or avg == 0:
        bowl[i] = 0

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


In [21]:
args=np.argsort(bowl)[-15:]
args

array([ 3126,  1831,  8858,  8803,  6664, 11827,  9356,  1544,  4700,
        4368,  4174,  9636,  8156,  2260,  2848], dtype=int64)

In [52]:
runs_metric_20 = []
player_dict_temp_20 = {}


for i in player_names:
    no_of_wickets=0
    no_balls = 0
    spf_sum = 0
    no_series = 0
    for j in player_dict_temp_3[i]:
        spf_sum += bowl[j]
        no_series += 1
        no_of_wickets += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 4000):    
    if(no_of_wickets > 150): 
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_20[i] = spf_sum/no_series
    
s_20 = [(k,player_dict_temp_20[k]) for k in sorted(player_dict_temp_20, key=player_dict_temp_20.get, reverse = True)]
s =0
for k,v in s_20:
    s += v
    print(k,":",v)
a_2 = s/len(s_20)  

Shoaib Akhtar : 2.412168539067178
Muralitharan M : 1.6204782664621757
Grimmett C V : 1.6153989261778898
Steyn D W : 1.5751270687135706
Pollock S M : 1.520636012460543
Tate M W : 1.517051161412256
Imran Khan : 1.4370881076494681
Hadlee R J : 1.4164486675524808
McGrath G D : 1.3892054073515612
Jadeja R A : 1.388141270089339
Lock G A R : 1.3623266739446565
Donald A A : 1.3451583014617035
Garner J : 1.337030957338947
Philander V D : 1.3245697000030319
Trueman F S : 1.3090021139655286
Martin C S : 1.3031096818656729
Ashwin R : 1.301997434756432
Ambrose C E L : 1.2937273911182725
Davidson A K : 1.2805282529497881
Laker J C : 1.2802898098020108
Boult T A : 1.2629017903418662
Miller K R : 1.2621884850211986
Yasir Shah : 1.2590953878659479
Gillespie J N : 1.2455695798763189
Marshall M D : 1.2436030388846866
Waqar Younis : 1.2327004643936994
Warne S K : 1.2323193498736216
Holding M A : 1.2142882175008503
Streak H H : 1.2135949038565208
Anderson J M : 1.213310218573031
Hazlewood J R : 1.212608443

In [53]:
bowl1=np.zeros(len(df1.index))
for i in df1.index:
    bowl1[i] = (wtrps[series_code[i]] - weighted_runs_arr[i])/(tops[series_code[i]]-df1["Overs"][i])
    e_r = df1["E/R"][i]
    bowl1[i] = bowl1[i]/e_r
    if e_r == 0:
        bowl1[i] = 0
bowl1[:14]

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


array([0.47028799, 0.48063638, 0.34027276, 0.56048722, 0.59506265,
       0.3302795 , 0.7887343 , 0.17182126, 0.6016263 , 0.56366939,
       0.58347044, 1.05244623, 0.52670711, 0.53808851])

In [54]:
runs_metric_30 = []
player_dict_temp_30 = {}


for i in player_names:
    no_of_wickets1=0
    spf_sum1 = 0
    no_series1 = 0
    no_balls = 0
    for j in player_dict_temp_3[i]:
        spf_sum1 += bowl1[j]
        no_series1 += 1
        no_of_wickets1 += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 4000):  
    if(no_of_wickets1 > 150): 
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_30[i] = spf_sum1/no_series1
    
s_30 = [(k,player_dict_temp_30[k]) for k in sorted(player_dict_temp_30, key=player_dict_temp_30.get, reverse = True)]

s =0
for k,v in s_30:
    s += v
    print(k,":",v)
a_3 = s/len(s_30)

Tate M W : 1.4538391155563775
Gibbs L R : 1.3318230113454217
Jadeja R A : 1.3162564942812849
Johnston W A : 1.296669726042012
Tayfield H J : 1.2861470456336905
Davidson A K : 1.2285226226707202
Iqbal Qasim M : 1.2258756374694135
Titmus F J : 1.206623963409111
Vettori D L : 1.2053850689888677
Sarfraz Nawaz : 1.1870529572376494
Miller K R : 1.1726683628767822
Muralitharan M : 1.171910975336873
Pollock S M : 1.1623483502786387
Bedi B S : 1.1572805875728598
McGrath G D : 1.1494598282792317
Underwood D L : 1.1398251056183513
Lock G A R : 1.1358495330943679
Philander V D : 1.1339358641852626
Sobers G S A : 1.1325982840509723
Ramadhin S : 1.131241191888941
Hazlewood J R : 1.1292138161330239
Benaud R : 1.1250003710938694
Ambrose C E L : 1.1230888180368832
Grimmett C V : 1.1225254822022483
Boult T A : 1.1135497090240618
Laker J C : 1.1081798185209868
Vaas W P U J C : 1.1051689643194855
Saqlain Mushtaq : 1.1044649963098814
Herath H M R K B : 1.1038417585576974
Saeed Ajmal : 1.103210441736001
Imr

In [55]:
bowl2=np.zeros(len(df1.index))
for i in df1.index:
    bowl2[i] = (tbps[series_code[i]] - balls[i])/(twps[series_code[i]]-df1["Wickets"][i])
    s_r = df1["S/R"][i]
    bowl2[i] = bowl2[i]/s_r
    if np.isnan(s_r) or s_r == 0:
        bowl2[i] = 0

In [56]:
runs_metric_40 = []
player_dict_temp_40 = {}


for i in player_names:
    no_of_wickets2=0
    spf_sum2 = 0
    no_series2 = 0
    no_balls = 0
    for j in player_dict_temp_3[i]:
        spf_sum2 += bowl2[j]
        no_series2 += 1
        no_of_wickets2 += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 4000):
    if(no_of_wickets2 > 150):    
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_40[i] = spf_sum2/no_series2
    
s_40 = [(k,player_dict_temp_40[k]) for k in sorted(player_dict_temp_40, key=player_dict_temp_40.get, reverse = True)]

s_1 =0
for k,v in s_40:
    s_1 += v
    print(k,":",v)
a_4 = s_1/len(s_40) 

Shoaib Akhtar : 1.7514651096197866
Steyn D W : 1.5968962684187467
Trueman F S : 1.5132970119298417
Donald A A : 1.416850313736199
Hadlee R J : 1.341327949272974
Hall W W : 1.3255896553710127
Grimmett C V : 1.3239702438811587
Waqar Younis : 1.3189361787958027
Marshall M D : 1.2923674267250225
MacGill S C G : 1.2690769531614952
Holding M A : 1.2543277020416774
Hughes M G : 1.2495443041544008
Imran Khan : 1.2379437706746481
Lee B : 1.237442257420067
Johnson M G : 1.2366641245994383
Muralitharan M : 1.2264669567368662
Garner J : 1.224770951801296
Willis R G D : 1.220284823319639
Starc M A : 1.214828944650203
Gough D : 1.209994386038261
Ashwin R : 1.1961071950518514
Snow J A : 1.1938676836062574
Yasir Shah : 1.1921797492451365
Botham I T : 1.1849757121685545
Fraser A R C : 1.1830864754495343
Pollock S M : 1.1800345298211121
Cairns C L : 1.1787897467062252
Umar Gul : 1.1764098244707983
Martin C S : 1.1736503329541919
Lillee D K : 1.1711721409413365
Edwards F H : 1.1637533622377487
Laker J C 

In [57]:
avg = [a_2, a_3, a_4]
w = np.average(avg)/avg

array([0.94213151, 1.06068016, 1.00423205])

In [58]:
player_dict_temp_50 = {}

for i in player_dict_temp_40.keys():
    player_dict_temp_50[i] = (w[0]*player_dict_temp_20[i]+w[1]*player_dict_temp_30[i]+w[2]*player_dict_temp_40[i])/np.sum(w)
    
s_50 = [(k,player_dict_temp_50[k]) for k in sorted(player_dict_temp_50, key=player_dict_temp_50.get, reverse = True)]

for k,v in s_50:
    print(k,":",v)

Shoaib Akhtar : 1.698185946124763
Steyn D W : 1.3561379007901642
Grimmett C V : 1.3442212577189085
Muralitharan M : 1.3306703051309774
Tate M W : 1.309181121573127
Pollock S M : 1.2805092945859433
Imran Khan : 1.2484170019917684
Hadlee R J : 1.2419391964628896
Jadeja R A : 1.2362071684031024
McGrath G D : 1.2237109220894455
Trueman F S : 1.2168876891122582
Donald A A : 1.2110927855196285
Lock G A R : 1.2091523605265253
Garner J : 1.2041137915502174
Philander V D : 1.1974670287212144
Laker J C : 1.1797560119013357
Davidson A K : 1.1724787139385626
Ambrose C E L : 1.1674736721924202
Ashwin R : 1.162368994280065
Marshall M D : 1.155544267378339
Miller K R : 1.1550077680217823
Boult T A : 1.1465116370215709
Waqar Younis : 1.1378536225279203
Gillespie J N : 1.1327818706072348
Martin C S : 1.1325698970191114
Holding M A : 1.132426636684467
Yasir Shah : 1.1293585217297484
Johnston W A : 1.1243055532742068
Hazlewood J R : 1.1231646861891866
Warne S K : 1.1187565132776076
Anderson J M : 1.11796

In [59]:
for k,v in s_50:
    first = player_indices[np.where(player_names == k)[0][0]]
    #print(first,"->",df[' Decade_Index '][first])
    if df1['Decade_Index'][first] >= 6:
        print(k,":",v)

Shoaib Akhtar : 1.698185946124763
Steyn D W : 1.3561379007901642
Muralitharan M : 1.3306703051309774
Pollock S M : 1.2805092945859433
Jadeja R A : 1.2362071684031024
McGrath G D : 1.2237109220894455
Donald A A : 1.2110927855196285
Philander V D : 1.1974670287212144
Ambrose C E L : 1.1674736721924202
Ashwin R : 1.162368994280065
Boult T A : 1.1465116370215709
Waqar Younis : 1.1378536225279203
Gillespie J N : 1.1327818706072348
Martin C S : 1.1325698970191114
Yasir Shah : 1.1293585217297484
Hazlewood J R : 1.1231646861891866
Warne S K : 1.1187565132776076
Anderson J M : 1.1179602632187877
Wasim Akram : 1.1159376679301076
Kumble A : 1.1002878963919946
Johnson M G : 1.097515846215612
Streak H H : 1.0934762103713125
Morkel M : 1.0915744585612108
Herath H M R K B : 1.0914609358023688
Swann G P : 1.0831081959325692
Vaas W P U J C : 1.0830182544478997
MacGill S C G : 1.0806251486689011
Saqlain Mushtaq : 1.0763786976077476
Fraser A R C : 1.0740612504824165
Harmison S J : 1.0711169144842427
Lee 

In [78]:
def name(bowl, x):
    runs_metric = []
    player_dict_temp = {}


    for i in player_names:
        no_of_wickets=0
        spf_sum = 0
        no_series = 0
        no_balls = 0
        for j in player_dict_temp_3[i]:
            spf_sum += bowl[j]
            no_series += 1
            no_of_wickets += df1["Wickets"][j]
            #no_balls += balls[j]
        #if(no_balls > 4000):
        if(no_of_wickets > x):    
            #runs_metric_20.append(runs/no_of_matches)
            player_dict_temp[i] = spf_sum/no_series

    sum_values =sum(player_dict_temp.values())
    '''for k,v in s:
        sum_values += v
        #print(k,":",v)'''
    a = sum_values/len(player_dict_temp) 
    return player_dict_temp, a

In [107]:
player_dict_temp_25, a_25 = name(bowl, 50)
player_dict_temp_35, a_35 = name(bowl1, 50)
player_dict_temp_45, a_45 = name(bowl2, 50)
avg_temp = [a_25, a_35, a_45]
w_temp = np.average(avg_temp)/avg_temp

player_dict_temp_55 = {}

for i in player_dict_temp_45.keys():
    player_dict_temp_55[i] = (w_temp[0]*player_dict_temp_25[i]+w_temp[1]*player_dict_temp_35[i]+w_temp[2]*player_dict_temp_45[i])/np.sum(w)

s_55 = [(k,player_dict_temp_55[k]) for k in sorted(player_dict_temp_55, key=player_dict_temp_55.get, reverse = True)]

In [118]:
players_list = {}
for country in series_to_number.keys():
    #print(country)
    count=0
    players_list[country] = list()
    for k,v in s_50:
        first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
        if df1['Country'][first] == country:
            player = str(k)+':'+str(v)
            players_list[country] = players_list[country]+[player]
            count += 1
        if count == 5:
            break
    if count < 5:
        players_list[country] = list()
        count = 0
        for k,v in s_55:
            first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
            if df1['Country'][first] == country:
                player = str(k)+':'+str(v)
                players_list[country] = players_list[country]+[player]
                count += 1
            if count == 5:
                break
for k in players_list.keys():
    print(k)
    for i in players_list[k]:
        print(i)
    print("\n")   

Australia
Grimmett C V:1.3442212577189085
McGrath G D:1.2237109220894455
Davidson A K:1.1724787139385626
Miller K R:1.1550077680217823
Gillespie J N:1.1327818706072348


Pakistan
Shoaib Akhtar:1.698185946124763
Imran Khan:1.2484170019917684
Waqar Younis:1.1378536225279203
Yasir Shah:1.1293585217297484
Wasim Akram:1.1159376679301076


New Zealand
Hadlee R J:1.2419391964628896
Boult T A:1.1465116370215709
Martin C S:1.1325698970191114
Southee T G:1.0509771023402594
Cairns C L:1.0502327884886098


West Indies
Garner J:1.2041137915502174
Ambrose C E L:1.1674736721924202
Marshall M D:1.155544267378339
Holding M A:1.132426636684467
Hall W W:1.1041279989986987


England
Tate M W:1.309181121573127
Trueman F S:1.2168876891122582
Lock G A R:1.2091523605265253
Laker J C:1.1797560119013357
Anderson J M:1.1179602632187877


India
Jadeja R A:1.2362071684031024
Ashwin R:1.162368994280065
Kumble A:1.1002878963919946
Khan Z:1.0653067897464719
Kapil Dev:1.0553986411882645


Sri Lanka
Muralitharan M:1.33

In [117]:
players_list = {}
for country in series_to_number.keys():
    #print(country)
    count=0
    players_list[country] = list()
    for k,v in s_50:
        first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
        if df1['Country'][first] == country and df1['Decade_Index'][first] >= 6:
            player = str(k)+':'+str(v)
            players_list[country] = players_list[country]+[player]
            count += 1
        if count == 5:
            break
    if count < 5:
        players_list[country] = list()
        count = 0
        for k,v in s_55:
            first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
            if df1['Country'][first] == country and df1['Decade_Index'][first] >= 6:
                player = str(k)+':'+str(v)
                players_list[country] = players_list[country]+[player]
                count += 1
            if count == 5:
                break
for k in players_list.keys():
    print(k)
    for i in players_list[k]:
        print(i)
    print("\n")

Australia
McGrath G D:1.2237109220894455
Gillespie J N:1.1327818706072348
Hazlewood J R:1.1231646861891866
Warne S K:1.1187565132776076
Johnson M G:1.097515846215612


Pakistan
Shoaib Akhtar:1.698185946124763
Waqar Younis:1.1378536225279203
Yasir Shah:1.1293585217297484
Wasim Akram:1.1159376679301076
Saqlain Mushtaq:1.0763786976077476


New Zealand
Boult T A:1.1465116370215709
Martin C S:1.1325698970191114
Southee T G:1.0509771023402594
Cairns C L:1.0502327884886098
Vettori D L:1.019474447913596


West Indies
Ambrose C E L:1.1676309405018972
Walsh C A:1.0575954876705727
Bishop I R:1.0035768484791627
Collymore C D:0.9843518605691612
Benjamin W K M:0.9631117190771809


England
Anderson J M:1.1179602632187877
Swann G P:1.0831081959325692
Fraser A R C:1.0740612504824165
Harmison S J:1.0711169144842427
Broad S C J:1.0227209983256302


India
Jadeja R A:1.2362071684031024
Ashwin R:1.162368994280065
Kumble A:1.1002878963919946
Khan Z:1.0653067897464719
Srinath J:1.0547540881314499


Sri Lanka
