In [123]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
df1 = pd.read_csv("records_final_series_test_final_bowlers_v6.csv")

In [19]:
df1.head()

Player    Country  Mat  Overs  Maidens  Runs  Wickets  Best  5w  \
0    Garrett T W  Australia    2   26.1       12    48        2  2|22   0   
1    Gregory D W  Australia    2    5.0        1     9        0   0|0   0   
2     Hodges J H  Australia    2   34.0        9    84        6   2|7   0   
3      Kendall T  Australia    2  140.3       56   215       14  7|55   1   
4  Midwinter W E  Australia    2  107.1       44   156        8  5|78   1   

   10w    Avg    S/R   E/R  Series_Code   H/A  Decade_Index  
0    0  24.00  52.50  2.74            1  Home             0  
1    0    NaN    NaN  2.70            1  Home             0  
2    0  14.00  22.67  3.71            1  Home             0  
3    0  15.36  40.21  2.29            1  Home             0  
4    0  19.50  53.63  2.18            1  Home             0

In [22]:
series = df1['Decade_Index'].values
number, series_unique = np.unique(series, return_inverse = True)

In [29]:
players = df1['Player'].values
player_names, player_indices = np.unique(players, return_index = True)
player_dict_temp_3 = {}
for i in df1.index:
    if df1["Player"][i] in player_dict_temp_3.keys():
        player_dict_temp_3[df1["Player"][i]] = player_dict_temp_3[df1["Player"][i]] + [i]
    else:
        player_dict_temp_3[df1["Player"][i]] = [i]

In [36]:
series_codes = df1['Series_Code'].values
series_list, series_occurances, series_code = np.unique(series_codes, return_index=True, return_inverse = True)
series_code

array([  0,   0,   0, ..., 722, 722, 722], dtype=int64)

In [31]:
series_to_number = {'Australia':0, 'Pakistan':1, 'New Zealand':2, 'West Indies':3, 'England':4, 'India' :5, 'Sri Lanka':6, 'Bangladesh':7, 'Zimbabwe':8, 'South Africa':9} 
opposition_country =[]
series_country = []
j = 0
for i in series_occurances:
    home = 0
    away = 0
    j = i
    while 1 != 0:
        #print(j)
        if df1['H/A'][j] == 'Home' and home == 0:
            #print(df['Country'][j])
            series_country.append(series_to_number[df1['Country'][j]]) 
            home = home + 1
        elif df1['H/A'][j] == 'Away' and away == 0:    
            #print(df['Country'][j])
            opposition_country.append(series_to_number[df1['Country'][j]]) 
            away = away + 1
        elif home == 1 and away == 1:
            #print("hello")
            break
        j = j + 1 

In [140]:
trps = np.zeros(723)
twps = np.zeros(723)
tops = np.zeros(723)
tbps = np.zeros(723)
balls = np.zeros(len(df1.index))
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        trps[series_code[i]] += df1["Runs"][i]
        twps[series_code[i]] += df1["Wickets"][i]
        balls[i] = math.floor(df1["Overs"][i])*6 + (df1["Overs"][i]- math.floor(df1["Overs"][i]))*10
        tbps[series_code[i]] += balls[i]
        
    tops[series_code[i]] += df1["Overs"][i]


In [144]:
balls[2848]

18.0

In [101]:
bowl=np.zeros(len(df1.index))
for i in df1.index:
    bowl[i] = (trps[series_code[i]] - df1["Runs"][i])/(twps[series_code[i]]-df1["Wickets"][i])
    avg = df1["Avg"][i]
    bowl[i] = bowl[i]/avg
    if np.isnan(avg) or avg == 0:
        bowl[i] = 0

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


In [108]:
args=np.argsort(bowl)[-15:]
args

array([11827, 10144,  8858,  1544,  1831,  9356,  8803,  6664,  4700,
        4368,  4174,  8156,  9636,  2848,  2260], dtype=int64)

In [199]:
runs_metric_20 = []
player_dict_temp_20 = {}


for i in player_names:
    no_of_wickets=0
    no_balls = 0
    spf_sum = 0
    no_series = 0
    for j in player_dict_temp_3[i]:
        spf_sum += bowl[j]
        no_series += 1
        no_of_wickets += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 3000):    
    if(no_of_wickets > 150): 
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_20[i] = spf_sum/no_series
    
s_20 = [(k,player_dict_temp_20[k]) for k in sorted(player_dict_temp_20, key=player_dict_temp_20.get, reverse = True)]
s =0
for k,v in s_20:
    s += v
    print(k,":",v)
a_2 = s/len(s_20)  

Shoaib Akhtar : 2.314361249029531
Grimmett C V : 1.7410466170706071
Steyn D W : 1.5870404904319095
Tate M W : 1.571723700200697
Muralitharan M : 1.5658753780027825
Pollock S M : 1.5102307156212682
McGrath G D : 1.4625151909537213
Garner J : 1.440187457127005
Jadeja R A : 1.4382778587426894
Ambrose C E L : 1.4324245514926408
Imran Khan : 1.4192092098821598
Lock G A R : 1.3948859980673967
Marshall M D : 1.361403032513139
Laker J C : 1.3598015539963175
Hadlee R J : 1.359604557996531
Trueman F S : 1.3565029148796246
Donald A A : 1.3434505494146924
Holding M A : 1.3398163038759219
Ashwin R : 1.338208312223292
Philander V D : 1.33664156494084
Miller K R : 1.3361482141114573
Davidson A K : 1.3360029532661464
Gillespie J N : 1.3298615885894967
Hazlewood J R : 1.3125695038484437
Johnston W A : 1.3050812101040348
Warne S K : 1.2802671493173834
Lillee D K : 1.2727584076439544
Anderson J M : 1.2597597811762906
Johnson M G : 1.2482728345375773
McKenzie G D : 1.2445382646797716
Yasir Shah : 1.242237

In [200]:
bowl1=np.zeros(len(df1.index))
for i in df1.index:
    bowl1[i] = (trps[series_code[i]] - df1["Runs"][i])/(tops[series_code[i]]-df1["Overs"][i])
    e_r = df1["E/R"][i]
    bowl1[i] = bowl1[i]/e_r
    if e_r == 0:
        bowl1[i] = 0
bowl1[:14]

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


array([0.52028784, 0.53173645, 0.37644971, 0.62007683, 0.65832823,
       0.36539399, 0.87259057, 0.19008887, 0.66558971, 0.62359731,
       0.64550357, 1.1643397 , 0.58270531, 0.59529674])

In [201]:
runs_metric_30 = []
player_dict_temp_30 = {}


for i in player_names:
    no_of_wickets1=0
    spf_sum1 = 0
    no_series1 = 0
    no_balls = 0
    for j in player_dict_temp_3[i]:
        spf_sum1 += bowl1[j]
        no_series1 += 1
        no_of_wickets1 += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 3000):  
    if(no_of_wickets1 > 150): 
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_30[i] = spf_sum1/no_series1
    
s_30 = [(k,player_dict_temp_30[k]) for k in sorted(player_dict_temp_30, key=player_dict_temp_30.get, reverse = True)]

s =0
for k,v in s_30:
    s += v
    print(k,":",v)
a_3 = s/len(s_30)

Tate M W : 1.4975083934811608
Gibbs L R : 1.4303511370198703
Johnston W A : 1.4086207697797464
Jadeja R A : 1.3557325914241156
Tayfield H J : 1.3086839564847592
Davidson A K : 1.2848427580566166
Titmus F J : 1.2733234588433588
Miller K R : 1.2485122246977884
Ambrose C E L : 1.2398140853453015
Iqbal Qasim M : 1.2212976090853775
McGrath G D : 1.2158594149434059
Sobers G S A : 1.2112644042509608
Grimmett C V : 1.2061697207227369
Benaud R : 1.2032064998042504
Sarfraz Nawaz : 1.1963568159678872
Hazlewood J R : 1.193078537773975
Bedi B S : 1.192933337997659
Ramadhin S : 1.1916507100384974
Lock G A R : 1.1809441475051239
Laker J C : 1.1776048483886943
Underwood D L : 1.1773195858344694
Pollock S M : 1.1690201712778072
Garner J : 1.1527455224649745
Lindwall R R : 1.142797256446144
Philander V D : 1.1387133831177414
Vettori D L : 1.1369492740933886
Muralitharan M : 1.1349283126921175
Siddle P M : 1.1109569965178188
Bedser A V : 1.110296306594125
Venkataraghavan S : 1.1101642765205244
Kallis J H

In [202]:
bowl2=np.zeros(len(df1.index))
for i in df1.index:
    bowl2[i] = (tbps[series_code[i]] - balls[i])/(twps[series_code[i]]-df1["Wickets"][i])
    s_r = df1["S/R"][i]
    bowl2[i] = bowl2[i]/s_r
    if np.isnan(s_r) or s_r == 0:
        bowl2[i] = 0

In [203]:
runs_metric_40 = []
player_dict_temp_40 = {}


for i in player_names:
    no_of_wickets2=0
    spf_sum2 = 0
    no_series2 = 0
    no_balls = 0
    for j in player_dict_temp_3[i]:
        spf_sum2 += bowl2[j]
        no_series2 += 1
        no_of_wickets2 += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 3000):
    if(no_of_wickets2 > 150):    
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_40[i] = spf_sum2/no_series2
    
s_40 = [(k,player_dict_temp_40[k]) for k in sorted(player_dict_temp_40, key=player_dict_temp_40.get, reverse = True)]

s_1 =0
for k,v in s_40:
    s_1 += v
    print(k,":",v)
a_4 = s_1/len(s_40) 

Shoaib Akhtar : 1.7514651096197866
Steyn D W : 1.5968962684187467
Trueman F S : 1.5132970119298417
Donald A A : 1.416850313736199
Hadlee R J : 1.341327949272974
Hall W W : 1.3255896553710127
Grimmett C V : 1.3239702438811587
Waqar Younis : 1.3189361787958027
Marshall M D : 1.2923674267250225
MacGill S C G : 1.2690769531614952
Holding M A : 1.2543277020416774
Hughes M G : 1.2495443041544008
Imran Khan : 1.2379437706746481
Lee B : 1.237442257420067
Johnson M G : 1.2366641245994383
Muralitharan M : 1.2264669567368662
Garner J : 1.224770951801296
Willis R G D : 1.220284823319639
Starc M A : 1.214828944650203
Gough D : 1.209994386038261
Ashwin R : 1.1961071950518514
Snow J A : 1.1938676836062574
Yasir Shah : 1.1921797492451365
Botham I T : 1.1849757121685545
Fraser A R C : 1.1830864754495343
Pollock S M : 1.1800345298211121
Cairns C L : 1.1787897467062252
Umar Gul : 1.1764098244707983
Martin C S : 1.1736503329541919
Lillee D K : 1.1711721409413365
Edwards F H : 1.1637533622377487
Laker J C 

In [204]:
avg = [a_2, a_3, a_4]
w = np.average(avg)/avg
w

array([0.93473205, 1.0503749 , 1.02235515])

In [205]:
player_dict_temp_50 = {}

for i in player_dict_temp_40.keys():
    player_dict_temp_50[i] = (w[0]*player_dict_temp_20[i]+w[1]*player_dict_temp_30[i]+w[2]*player_dict_temp_40[i])/np.sum(w)
    
s_50 = [(k,player_dict_temp_50[k]) for k in sorted(player_dict_temp_50, key=player_dict_temp_50.get, reverse = True)]

for k,v in s_50:
    print(k,":",v)

Shoaib Akhtar : 1.656846922422107
Grimmett C V : 1.4124567921620843
Steyn D W : 1.3651580276868753
Tate M W : 1.338322344192285
Muralitharan M : 1.2999860993724248
Pollock S M : 1.2788140794799085
McGrath G D : 1.2690706186452485
Garner J : 1.2665679900176199
Jadeja R A : 1.2635605598441344
Ambrose C E L : 1.2507585625705873
Trueman F S : 1.247327309256259
Imran Khan : 1.2412808422035937
Lock G A R : 1.2344964241843548
Laker J C : 1.2286008442745133
Marshall M D : 1.2199961467542306
Donald A A : 1.2139170235547376
Hadlee R J : 1.2099570270962468
Davidson A K : 1.207965212820062
Miller K R : 1.203441149092387
Philander V D : 1.2024783672029458
Holding M A : 1.1997789187029053
Johnston W A : 1.1919117606929819
Ashwin R : 1.1853479398547082
Gillespie J N : 1.1812863830236937
Hazlewood J R : 1.1757532077731645
Hall W W : 1.1508555155318612
Warne S K : 1.1506753186512086
Lillee D K : 1.1481025178998265
Anderson J M : 1.1455143515957824
Johnson M G : 1.1416015814467486
McKenzie G D : 1.14137