In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df1 = pd.read_csv("records_final_series_test_final_bowlers_v6.csv")

In [3]:
df1.head()

Player    Country  Mat  Overs  Maidens  Runs  Wickets  Best  5w  \
0    Garrett T W  Australia    2   26.1       12    48        2  2|22   0   
1    Gregory D W  Australia    2    5.0        1     9        0   0|0   0   
2     Hodges J H  Australia    2   34.0        9    84        6   2|7   0   
3      Kendall T  Australia    2  140.3       56   215       14  7|55   1   
4  Midwinter W E  Australia    2  107.1       44   156        8  5|78   1   

   10w    Avg    S/R   E/R  Series_Code   H/A  Decade_Index  
0    0  24.00  52.50  2.74            1  Home             0  
1    0    NaN    NaN  2.70            1  Home             0  
2    0  14.00  22.67  3.71            1  Home             0  
3    0  15.36  40.21  2.29            1  Home             0  
4    0  19.50  53.63  2.18            1  Home             0

In [4]:
#df1.sort_values(['Series_Code', 'Mat'], ascending=[True, False], inplace=True)

In [5]:
#df1

In [6]:
series = df1['Decade_Index'].values
number, series_unique = np.unique(series, return_inverse = True)

In [7]:
players = df1['Player'].values
player_names, player_indices = np.unique(players, return_index = True)
player_dict_temp_3 = {}
for i in df1.index:
    if df1["Player"][i] in player_dict_temp_3.keys():
        player_dict_temp_3[df1["Player"][i]] = player_dict_temp_3[df1["Player"][i]] + [i]
    else:
        player_dict_temp_3[df1["Player"][i]] = [i]

In [8]:
series_codes = df1['Series_Code'].values
series_list, series_occurances, series_code = np.unique(series_codes, return_index=True, return_inverse = True)
series_code

array([  0,   0,   0, ..., 722, 722, 722], dtype=int64)

In [9]:
series_to_number = {'Australia':0, 'Pakistan':1, 'New Zealand':2, 'West Indies':3, 'England':4, 'India' :5, 'Sri Lanka':6, 'Bangladesh':7, 'Zimbabwe':8, 'South Africa':9} 
opposition_country =[]
series_country = []
j = 0
for i in series_occurances:
    home = 0
    away = 0
    j = i
    while 1 != 0:
        #print(j)
        if df1['H/A'][j] == 'Home' and home == 0:
            #print(df['Country'][j])
            series_country.append(series_to_number[df1['Country'][j]]) 
            home = home + 1
        elif df1['H/A'][j] == 'Away' and away == 0:    
            #print(df['Country'][j])
            opposition_country.append(series_to_number[df1['Country'][j]]) 
            away = away + 1
        elif home == 1 and away == 1:
            #print("hello")
            break
        j = j + 1 

In [10]:
series_country

[0,
 0,
 4,
 0,
 4,
 0,
 4,
 0,
 4,
 0,
 0,
 4,
 9,
 4,
 0,
 9,
 4,
 0,
 9,
 4,
 0,
 9,
 4,
 0,
 4,
 9,
 0,
 4,
 9,
 4,
 0,
 4,
 9,
 0,
 0,
 9,
 0,
 4,
 9,
 9,
 4,
 0,
 4,
 9,
 4,
 0,
 4,
 2,
 3,
 4,
 0,
 9,
 4,
 0,
 2,
 4,
 0,
 2,
 4,
 5,
 4,
 3,
 4,
 9,
 4,
 0,
 4,
 4,
 9,
 4,
 2,
 4,
 0,
 2,
 4,
 0,
 3,
 4,
 5,
 9,
 4,
 9,
 4,
 0,
 2,
 4,
 5,
 0,
 2,
 4,
 5,
 0,
 3,
 2,
 4,
 9,
 3,
 4,
 0,
 1,
 2,
 3,
 4,
 1,
 5,
 2,
 4,
 1,
 5,
 9,
 4,
 9,
 3,
 4,
 5,
 0,
 1,
 2,
 4,
 1,
 5,
 3,
 4,
 5,
 0,
 4,
 1,
 5,
 9,
 3,
 4,
 0,
 2,
 4,
 0,
 5,
 2,
 4,
 5,
 1,
 0,
 9,
 2,
 5,
 3,
 1,
 4,
 4,
 0,
 2,
 4,
 5,
 9,
 4,
 4,
 0,
 3,
 2,
 4,
 0,
 1,
 2,
 4,
 4,
 5,
 1,
 5,
 9,
 0,
 3,
 2,
 4,
 4,
 3,
 4,
 5,
 0,
 2,
 3,
 1,
 4,
 4,
 0,
 3,
 2,
 4,
 4,
 5,
 0,
 1,
 2,
 4,
 0,
 2,
 3,
 4,
 1,
 5,
 5,
 0,
 2,
 3,
 0,
 4,
 0,
 1,
 2,
 3,
 4,
 4,
 1,
 0,
 5,
 2,
 0,
 4,
 5,
 5,
 0,
 0,
 2,
 5,
 1,
 4,
 4,
 1,
 0,
 0,
 3,
 2,
 4,
 0,
 5,
 0,
 6,
 2,
 1,
 4,
 4,
 5,
 1,
 0,
 1,
 3,
 2,
 6,
 4,
 5,
 5,
 0,


In [11]:
len(series_country)

723

In [12]:
trps = np.zeros(723)
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        trps[series_code[i]] += df1["Runs"][i]

In [13]:
arpspc = np.zeros(10)
tmpc = np.zeros(10)
for i in range(len(trps)):
    tmpc[series_country[i]] += df1['Mat'][series_occurances[i]]
    arpspc[series_country[i]] += trps[i]

In [14]:
arpc=arpspc/tmpc

In [15]:
avr_average = np.average(arpc)

In [16]:
weights_arpc = np.average(arpc)/arpc

In [17]:
weights_arpc

array([0.90389964, 1.0380722 , 1.1192837 , 0.85252931, 0.95446444,
       0.96980682, 1.04872389, 1.03222664, 1.18738037, 0.97981671])

In [18]:
weighted_runs_arr = []
for i in df1.index:
    weighted_runs_arr.append(df1['Runs'][i]*weights_arpc[series_country[series_code[i]]])
weighted_runs_arr

[43.38718257177601,
 8.135096732208002,
 75.92756950060802,
 194.33842193608007,
 141.00834335827204,
 100.33285969723202,
 28.020888744272007,
 13.558494553680005,
 32.54038692883201,
 117.50695279856004,
 113.89135425091203,
 131.96934698915203,
 96.71726114958403,
 111.17965534017603,
 72.31197095296002,
 24.40529019662401,
 32.54038692883201,
 99.42896006032002,
 61.465175310016015,
 12.654594916768003,
 0.0,
 28.020888744272007,
 5.423397821472001,
 23.501390559712007,
 92.19776296502403,
 16.225895447617933,
 64.90358179047173,
 21.952682076188967,
 139.3518079618952,
 1.9089288761903451,
 60.13125959999587,
 125.0348413904676,
 65.8580462285669,
 105.94555262856416,
 87.81072830475587,
 10.499108819046898,
 21.952682076188967,
 144.12413015237107,
 31.63648729192001,
 122.02645098312003,
 180.77992738240005,
 232.30220668638407,
 331.7311667467041,
 48.81058039324802,
 27.11698910736001,
 13.558494553680005,
 245.86070124006406,
 471.83561046806415,
 115.69915352473603,
 55.1378

In [19]:
wtrps = np.zeros(723)
twps = np.zeros(723)
tops = np.zeros(723)
tbps = np.zeros(723)
balls = np.zeros(len(df1.index))
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        wtrps[series_code[i]] += weighted_runs_arr[i]
        twps[series_code[i]] += df1["Wickets"][i]
        balls[i] = math.floor(df1["Overs"][i])*6 + (df1["Overs"][i]- math.floor(df1["Overs"][i]))*10
        tbps[series_code[i]] += balls[i]
        
    tops[series_code[i]] += df1["Overs"][i]

In [20]:
bowl=np.zeros(len(df1.index))
for i in df1.index:
    bowl[i] = (wtrps[series_code[i]] - weighted_runs_arr[i])/(twps[series_code[i]]-df1["Wickets"][i])
    avg = df1["Avg"][i]
    bowl[i] = bowl[i]/avg
    if np.isnan(avg) or avg == 0:
        bowl[i] = 0

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


In [21]:
bowl1=np.zeros(len(df1.index))
for i in df1.index:
    bowl1[i] = (wtrps[series_code[i]] - weighted_runs_arr[i])/(tops[series_code[i]]-df1["Overs"][i])
    e_r = df1["E/R"][i]
    bowl1[i] = bowl1[i]/e_r
    if e_r == 0:
        bowl1[i] = 0
bowl1[:14]

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


array([0.47028799, 0.48063638, 0.34027276, 0.56048722, 0.59506265,
       0.3302795 , 0.7887343 , 0.17182126, 0.6016263 , 0.56366939,
       0.58347044, 1.05244623, 0.52670711, 0.53808851])

In [22]:
bowl2=np.zeros(len(df1.index))
for i in df1.index:
    bowl2[i] = (tbps[series_code[i]] - balls[i])/(twps[series_code[i]]-df1["Wickets"][i])
    s_r = df1["S/R"][i]
    bowl2[i] = bowl2[i]/s_r
    if np.isnan(s_r) or s_r == 0:
        bowl2[i] = 0

In [23]:
def name(bowl, x):
    runs_metric = []
    player_dict_temp = {}


    for i in player_names:
        no_of_wickets=0
        spf_sum = 0
        no_series = 0
        no_balls = 0
        for j in player_dict_temp_3[i]:
            spf_sum += bowl[j]
            no_series += 1
            no_of_wickets += df1["Wickets"][j]
            #no_balls += balls[j]
        #if(no_balls > 4000):
        if(no_of_wickets > x):    
            #runs_metric_20.append(runs/no_of_matches)
            player_dict_temp[i] = spf_sum/no_series

    sum_values =sum(player_dict_temp.values())
    '''for k,v in s:
        sum_values += v
        #print(k,":",v)'''
    a = sum_values/len(player_dict_temp) 
    return player_dict_temp, a

In [24]:
def final_players(x):
    player_dict_temp_25, a_25 = name(bowl, x)
    player_dict_temp_35, a_35 = name(bowl1, x)
    player_dict_temp_45, a_45 = name(bowl2, x)
    avg_temp = [a_25, a_35, a_45]
    print(avg_temp)
    w_temp = np.average(avg_temp)/avg_temp
    print(w_temp)

    player_dict_temp_55 = {}

    for i in player_dict_temp_45.keys():
        player_dict_temp_55[i] = (w_temp[0]*player_dict_temp_25[i]+w_temp[1]*player_dict_temp_35[i]+w_temp[2]*player_dict_temp_45[i])/np.sum(w_temp)

    s_55 = [(k,player_dict_temp_55[k]) for k in sorted(player_dict_temp_55, key=player_dict_temp_55.get, reverse = True)]
    return s_55

In [25]:
s_55 = final_players(50)

s_50 = final_players(150)

[0.9898727480758911, 0.9718831679223513, 0.9775521719221536]
[0.98979325 1.00811434 1.0022681 ]
[1.1443300432514851, 1.016432133861857, 1.0735660088580843]
[0.94213151 1.06068016 1.00423205]


In [30]:
for k,v in s_50:
    print(k,v)

Shoaib Akhtar 1.6981859461247635
Steyn D W 1.3561379007901644
Grimmett C V 1.3442212577189085
Muralitharan M 1.3306703051309774
Tate M W 1.309181121573127
Pollock S M 1.2805092945859435
Imran Khan 1.2484170019917686
Hadlee R J 1.2419391964628899
Jadeja R A 1.2362071684031029
McGrath G D 1.2237109220894458
Trueman F S 1.2168876891122584
Donald A A 1.2110927855196287
Lock G A R 1.2091523605265255
Garner J 1.2041137915502176
Philander V D 1.1974670287212146
Laker J C 1.179756011901336
Davidson A K 1.1724787139385628
Ambrose C E L 1.1674736721924204
Ashwin R 1.1623689942800652
Marshall M D 1.1555442673783392
Miller K R 1.1550077680217825
Boult T A 1.146511637021571
Waqar Younis 1.1378536225279208
Gillespie J N 1.132781870607235
Martin C S 1.1325698970191116
Holding M A 1.1324266366844673
Yasir Shah 1.1293585217297486
Johnston W A 1.124305553274207
Hazlewood J R 1.1231646861891869
Warne S K 1.1187565132776076
Anderson J M 1.117960263218788
Wasim Akram 1.1159376679301076
Lillee D K 1.1043531

In [26]:
players_list = {}
for country in series_to_number.keys():
    #print(country)
    count=0
    players_list[country] = list()
    for k,v in s_50:
        first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
        if df1['Country'][first] == country:
            player = str(k)+':'+str(v)
            players_list[country] = players_list[country]+[player]
            count += 1
        if count == 6:
            break
    if count < 5:
        players_list[country] = list()
        count = 0
        for k,v in s_55:
            first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
            if df1['Country'][first] == country:
                player = str(k)+':'+str(v)
                players_list[country] = players_list[country]+[player]
                count += 1
            if count == 6:
                break
for k in players_list.keys():
    print(k)
    for i in players_list[k]:
        print(i)
    print("\n")   

Australia
Grimmett C V:1.3442212577189085
McGrath G D:1.2237109220894458
Davidson A K:1.1724787139385628
Miller K R:1.1550077680217825
Gillespie J N:1.132781870607235
Johnston W A:1.124305553274207


Pakistan
Shoaib Akhtar:1.6981859461247635
Imran Khan:1.2484170019917686
Waqar Younis:1.1378536225279208
Yasir Shah:1.1293585217297486
Wasim Akram:1.1159376679301076
Saqlain Mushtaq:1.0763786976077476


New Zealand
Hadlee R J:1.2419391964628899
Boult T A:1.146511637021571
Martin C S:1.1325698970191116
Southee T G:1.0509771023402599
Cairns C L:1.05023278848861
Vettori D L:1.0194744479135962


West Indies
Garner J:1.2041137915502176
Ambrose C E L:1.1674736721924204
Marshall M D:1.1555442673783392
Holding M A:1.1324266366844673
Hall W W:1.1041279989986992
Roberts A M E:1.0637710639424678


England
Tate M W:1.309181121573127
Trueman F S:1.2168876891122584
Lock G A R:1.2091523605265255
Laker J C:1.179756011901336
Anderson J M:1.117960263218788
Swann G P:1.0831081959325695


India
Jadeja R A:1.23

In [27]:
players_list = {}
for country in series_to_number.keys():
    #print(country)
    count=0
    players_list[country] = list()
    for k,v in s_50:
        first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
        if df1['Country'][first] == country and df1['Decade_Index'][first] >= 6:
            player = str(k)+':'+str(v)
            players_list[country] = players_list[country]+[player]
            count += 1
        if count == 6:
            break
    if count < 5:
        players_list[country] = list()
        count = 0
        for k,v in s_55:
            first = player_indices[np.where(player_names == k)[0][0]]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
            if df1['Country'][first] == country and df1['Decade_Index'][first] >= 6:
                player = str(k)+':'+str(v)
                players_list[country] = players_list[country]+[player]
                count += 1
            if count == 6:
                break
for k in players_list.keys():
    print(k)
    for i in players_list[k]:
        print(i)
    print("\n")

Australia
McGrath G D:1.2237109220894458
Gillespie J N:1.132781870607235
Hazlewood J R:1.1231646861891869
Warne S K:1.1187565132776076
Johnson M G:1.0975158462156123
MacGill S C G:1.0806251486689014


Pakistan
Shoaib Akhtar:1.6981859461247635
Waqar Younis:1.1378536225279208
Yasir Shah:1.1293585217297486
Wasim Akram:1.1159376679301076
Saqlain Mushtaq:1.0763786976077476
Saeed Ajmal:1.0252393299133928


New Zealand
Boult T A:1.146511637021571
Martin C S:1.1325698970191116
Southee T G:1.0509771023402599
Cairns C L:1.05023278848861
Vettori D L:1.0194744479135962
Morrison D K:0.993086061955571


West Indies
Ambrose C E L:1.1703038898367921
Walsh C A:1.0600165430377264
Bishop I R:1.0058742439802664
Collymore C D:0.9866052460865747
Benjamin W K M:0.9653164815065065
Roach K A J:0.9629091641293498


England
Anderson J M:1.117960263218788
Swann G P:1.0831081959325695
Fraser A R C:1.0740612504824167
Harmison S J:1.071116914484243
Broad S C J:1.0227209983256305
Hoggard M J:1.020589129392341


India

In [28]:
s_51 = final_players(10)
s_56 = final_players(5)


[0.9070394399470981, 0.9511938650726244, 0.922570810900443]
[1.02193429 0.97449609 1.00473015]
[0.8897597187765746, 0.9456062675248209, 0.9126230455462321]
[1.02948732 0.96868684 1.00369627]


In [29]:

players_list = {}
for country in series_to_number.keys():
    #print(country)
    count=0
    players_list[country] = list()
    for k,v in s_51:
        last = player_dict_temp_3[k][-1]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
        if df1['Country'][last] == country and df1["Decade_Index"][last]>=13:
            player = str(k)+':'+str(v)
            players_list[country] = players_list[country]+[player]
            count += 1
        if count == 12:
            break
    if count < 7:
        players_list[country] = list()
        count = 0
        for k,v in s_56:
            last = player_dict_temp_3[k][-1]
        #print(first)
        #print(first,"->",df[' Decade_Index '][first])
            if df1['Country'][last] == country and df1['Decade_Index'][last] >= 13:
                player = str(k)+':'+str(v)
                players_list[country] = players_list[country]+[player]
                count += 1
            if count == 12:
                break
for k in players_list.keys():
    print(k)
    for i in players_list[k]:
        print(i)
    print("\n")   

Australia
Cummins P J:1.1293283358300552
Hazlewood J R:1.1253543533601653
Pattinson J L:1.1122777423994648
Starc M A:1.0394589618372672
Siddle P M:1.0387231272726152
O'Keefe S N J:1.0288540893280291
Lyon N M:0.9794361981863734
Bird J M:0.9674152907651512
Smith S P D:0.8055494914019656
Marsh M R:0.789004286374587


Pakistan
Imran Khan:1.2579598904282616
Yasir Shah:1.137835997225558
Mohammad Abbas:1.0580754955420375
Wahab Riaz:0.9916892013448518
Rahat Ali:0.9780174032911814
Zulfiqar Babar:0.9519106275064778
Mohammad Amir:0.8792693400732823
Sohail Khan:0.7434051488209857


New Zealand
Wagner N:1.1931767922838799
Boult T A:1.1505407460454649
Santner M J:1.114505254229795
de Grandhomme C:1.0687589420486727
Southee T G:1.053134432141944
Bracewell D A J:0.9736188445494739
Anderson C J:0.9124787380865861
Henry M J:0.8325385937863542
Craig M D:0.8225895052644725
Neesham J D S:0.8146524033016923
Sodhi I S:0.7818017407973696
Patel J S:0.7706512977570954


West Indies
Roach K A J:0.964497808328065