In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df1 = pd.read_csv("records_final_series_test_final_bowlers_v6.csv")

In [3]:
df1.head()

Player    Country  Mat  Overs  Maidens  Runs  Wickets  Best  5w  \
0    Garrett T W  Australia    2   26.1       12    48        2  2|22   0   
1    Gregory D W  Australia    2    5.0        1     9        0   0|0   0   
2     Hodges J H  Australia    2   34.0        9    84        6   2|7   0   
3      Kendall T  Australia    2  140.3       56   215       14  7|55   1   
4  Midwinter W E  Australia    2  107.1       44   156        8  5|78   1   

   10w    Avg    S/R   E/R  Series_Code   H/A  Decade_Index  
0    0  24.00  52.50  2.74            1  Home             0  
1    0    NaN    NaN  2.70            1  Home             0  
2    0  14.00  22.67  3.71            1  Home             0  
3    0  15.36  40.21  2.29            1  Home             0  
4    0  19.50  53.63  2.18            1  Home             0

In [4]:
df1.sort_values(['Series_Code', 'Mat'], ascending=[True, False], inplace=True)

In [5]:
df1

Player       Country  Mat  Overs  Maidens  Runs  Wickets  \
0          Garrett T W     Australia    2   26.1       12    48        2   
1          Gregory D W     Australia    2    5.0        1     9        0   
2           Hodges J H     Australia    2   34.0        9    84        6   
3            Kendall T     Australia    2  140.3       56   215       14   
4        Midwinter W E     Australia    2  107.1       44   156        8   
6           Thompson N     Australia    2   28.0       16    31        1   
7           Armitage T       England    2    3.0        0    15        0   
8             Emmett T       England    2   25.0       13    36        0   
9               Hill A       England    2   85.0       37   130        7   
10        Lillywhite J       England    2   85.0       37   126        8   
11              Shaw A       England    2  163.3       96   146        8   
12        Southerton J       England    2   65.3       30   107        7   
13            Ulyett G       England    2   77.1       34   123        6   
5        Spofforth F R     Australia    1   44.0        9   111        4   
14           Allan F E     Australia    1   45.0       15    80        4   
15           Boyle H F     Australia    1   17.0        5    27        2   
16         Garrett T W     Australia    1   15.0        6    36        1   
17       Spofforth F R     Australia    1   60.0       25   110       13   
18            Emmett T       England    1   59.0       31    68        7   
19            Harris L       England    1    3.0        0    14        0   
20          Hornby A N       England    1    7.0        7     0        1   
21           Lucas A P       England    1   18.0        6    31        0   
22         Royle V P F       England    1    4.0        1     6        0   
23         Schultz S S       England    1    8.0        3    26        1   
24            Ulyett G       England    1   63.0       24   102        1   
25            Barnes W       England    1    8.3        3    17        1   
26           Grace W G       England    1   29.1       10    68        3   
27           Lucas A P       England    1   12.0        7    23        0   
28            Morley F       England    1   93.0       39   146        8   
29              Penn F       England    1    3.0        1     2        0   
...                ...           ...  ...    ...      ...   ...      ...   
12312    Philander V D  South Africa    4  121.0       45   257       10   
12313         Rabada K  South Africa    4  137.5       39   436       23   
12314      Cummins P J     Australia    4  155.4       32   472       22   
12315    Hazlewood J R     Australia    4  160.0       30   471       12   
12316         Lyon N M     Australia    4  210.5       39   681       16   
12317        Marsh M R     Australia    4   42.0        6   169        4   
12310         Morkel M  South Africa    3   88.0       24   284       15   
12320      Smith S P D     Australia    3    7.0        4     9        0   
12321        Starc M A     Australia    3  109.2       18   413       12   
12305         Bavuma T  South Africa    2    1.0        0    10        0   
12306     de Bruyn T B  South Africa    2    2.0        0     6        0   
12311          Ngidi L  South Africa    1   26.3        8    75        5   
12318      Renshaw M T     Australia    1    4.0        0    13        0   
12319       Sayers C J     Australia    1   49.0       11   146        2   
12323        Boult T A   New Zealand    2   94.3       22   275       15   
12324  de Grandhomme C   New Zealand    2   67.0       16   178        4   
12326      Southee T G   New Zealand    2   81.0       18   238       12   
12327         Wagner N   New Zealand    2   74.4       21   197        5   
12328   Williamson K S   New Zealand    2    1.0        0     1        0   
12330     Anderson J M       England    2   62.0       20   172        7   
12331      Broad S C J       England    2   64.3       17   148 

In [6]:
series = df1['Decade_Index'].values
number, series_unique = np.unique(series, return_inverse = True)

In [7]:
players = df1['Player'].values
player_names, player_indices = np.unique(players, return_index = True)
player_dict_temp_3 = {}
for i in df1.index:
    if df1["Player"][i] in player_dict_temp_3.keys():
        player_dict_temp_3[df1["Player"][i]] = player_dict_temp_3[df1["Player"][i]] + [i]
    else:
        player_dict_temp_3[df1["Player"][i]] = [i]

In [8]:
series_codes = df1['Series_Code'].values
series_list, series_occurances, series_code = np.unique(series_codes, return_index=True, return_inverse = True)
series_code

array([  0,   0,   0, ..., 722, 722, 722], dtype=int64)

In [9]:
series_to_number = {'Australia':0, 'Pakistan':1, 'New Zealand':2, 'West Indies':3, 'England':4, 'India' :5, 'Sri Lanka':6, 'Bangladesh':7, 'Zimbabwe':8, 'South Africa':9} 
opposition_country =[]
series_country = []
j = 0
for i in series_occurances:
    home = 0
    away = 0
    j = i
    while 1 != 0:
        #print(j)
        if df1['H/A'][j] == 'Home' and home == 0:
            #print(df['Country'][j])
            series_country.append(series_to_number[df1['Country'][j]]) 
            home = home + 1
        elif df1['H/A'][j] == 'Away' and away == 0:    
            #print(df['Country'][j])
            opposition_country.append(series_to_number[df1['Country'][j]]) 
            away = away + 1
        elif home == 1 and away == 1:
            #print("hello")
            break
        j = j + 1 

In [10]:
series_country

[0,
 0,
 4,
 0,
 4,
 0,
 4,
 0,
 4,
 0,
 0,
 4,
 9,
 4,
 0,
 9,
 4,
 0,
 9,
 4,
 0,
 9,
 4,
 0,
 4,
 9,
 0,
 4,
 9,
 4,
 0,
 4,
 9,
 0,
 0,
 9,
 0,
 4,
 9,
 9,
 4,
 0,
 4,
 9,
 4,
 0,
 4,
 2,
 3,
 4,
 0,
 9,
 4,
 0,
 2,
 4,
 0,
 2,
 4,
 5,
 4,
 3,
 4,
 9,
 4,
 0,
 4,
 4,
 9,
 4,
 2,
 4,
 0,
 2,
 4,
 0,
 3,
 4,
 5,
 9,
 4,
 9,
 4,
 0,
 2,
 4,
 5,
 0,
 2,
 4,
 5,
 0,
 3,
 2,
 4,
 9,
 3,
 4,
 0,
 1,
 2,
 3,
 4,
 1,
 5,
 2,
 4,
 1,
 5,
 9,
 4,
 9,
 3,
 4,
 5,
 0,
 1,
 2,
 4,
 1,
 5,
 3,
 4,
 5,
 0,
 4,
 1,
 5,
 9,
 3,
 4,
 0,
 2,
 4,
 0,
 5,
 2,
 4,
 5,
 1,
 0,
 9,
 2,
 5,
 3,
 1,
 4,
 4,
 0,
 2,
 4,
 5,
 9,
 4,
 4,
 0,
 3,
 2,
 4,
 0,
 1,
 2,
 4,
 4,
 5,
 1,
 5,
 9,
 0,
 3,
 2,
 4,
 4,
 3,
 4,
 5,
 0,
 2,
 3,
 1,
 4,
 4,
 0,
 3,
 2,
 4,
 4,
 5,
 0,
 1,
 2,
 4,
 0,
 2,
 3,
 4,
 1,
 5,
 5,
 0,
 2,
 3,
 0,
 4,
 0,
 1,
 2,
 3,
 4,
 4,
 1,
 0,
 5,
 2,
 0,
 4,
 5,
 5,
 0,
 0,
 2,
 5,
 1,
 4,
 4,
 1,
 0,
 0,
 3,
 2,
 4,
 0,
 5,
 0,
 6,
 2,
 1,
 4,
 4,
 5,
 1,
 0,
 1,
 3,
 2,
 6,
 4,
 5,
 5,
 0,


In [11]:
len(series_country)

723

In [12]:
trps = np.zeros(723)
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        trps[series_code[i]] += df1["Runs"][i]

In [13]:
arpspc = np.zeros(10)
tmpc = np.zeros(10)
for i in range(len(trps)):
    tmpc[series_country[i]] += df1['Mat'][series_occurances[i]]
    arpspc[series_country[i]] += trps[i]

In [14]:
arpc=arpspc/tmpc

In [15]:
avr_average = np.average(arpc)

In [16]:
weights_arpc = np.average(arpc)/arpc

In [30]:
weights_arpc

array([ 0.90389964,  1.0380722 ,  1.1192837 ,  0.85252931,  0.95446444,
        0.96980682,  1.04872389,  1.03222664,  1.18738037,  0.97981671])

In [17]:
weighted_runs_arr = []
for i in df1.index:
    weighted_runs_arr.append(df1['Runs'][i]*weights_arpc[series_country[series_code[i]]])
weighted_runs_arr

[43.387182571776009,
 8.1350967322080017,
 75.927569500608016,
 194.33842193608007,
 141.00834335827204,
 28.020888744272007,
 13.558494553680005,
 32.540386928832007,
 117.50695279856004,
 113.89135425091203,
 131.96934698915203,
 96.717261149584033,
 111.17965534017603,
 100.33285969723202,
 72.311970952960024,
 24.405290196624009,
 32.540386928832007,
 99.428960060320023,
 61.465175310016015,
 12.654594916768003,
 0.0,
 28.020888744272007,
 5.4233978214720011,
 23.501390559712007,
 92.197762965024026,
 16.225895447617933,
 64.903581790471733,
 21.952682076188967,
 139.35180796189519,
 1.9089288761903451,
 60.131259599995872,
 125.03484139046761,
 65.858046228566906,
 105.94555262856416,
 87.81072830475587,
 10.499108819046898,
 21.952682076188967,
 144.12413015237107,
 122.02645098312003,
 13.558494553680005,
 245.86070124006406,
 471.83561046806415,
 55.137877851632012,
 301.90247872860806,
 162.70193464416005,
 231.39830704947207,
 68.696372405312019,
 162.70193464416005,
 31.6364

In [18]:
wtrps = np.zeros(723)
twps = np.zeros(723)
tops = np.zeros(723)
tbps = np.zeros(723)
balls = np.zeros(len(df1.index))
for i in df1.index:
    avg = df1["Avg"][i]
    if not np.isnan(avg):
        wtrps[series_code[i]] += weighted_runs_arr[i]
        twps[series_code[i]] += df1["Wickets"][i]
        balls[i] = math.floor(df1["Overs"][i])*6 + (df1["Overs"][i]- math.floor(df1["Overs"][i]))*10
        tbps[series_code[i]] += balls[i]
        
    tops[series_code[i]] += df1["Overs"][i]

In [19]:
bowl=np.zeros(len(df1.index))
for i in df1.index:
    bowl[i] = (wtrps[series_code[i]] - weighted_runs_arr[i])/(twps[series_code[i]]-df1["Wickets"][i])
    avg = df1["Avg"][i]
    bowl[i] = bowl[i]/avg
    if np.isnan(avg) or avg == 0:
        bowl[i] = 0

C:\Users\Vasthav\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


In [20]:
args=np.argsort(bowl)[-15:]
args

array([11130,  9356, 11827, 10716,  1831,  8803,  4174,  6664,  4368,
        1544,  4700,  9636,  8156,  2260,  2848], dtype=int64)

In [21]:
runs_metric_20 = []
player_dict_temp_20 = {}


for i in player_names:
    no_of_wickets=0
    no_balls = 0
    spf_sum = 0
    no_series = 0
    for j in player_dict_temp_3[i]:
        spf_sum += bowl[j]
        no_series += 1
        no_of_wickets += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 3000):    
    if(no_of_wickets > 150): 
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_20[i] = spf_sum/no_series
    
s_20 = [(k,player_dict_temp_20[k]) for k in sorted(player_dict_temp_20, key=player_dict_temp_20.get, reverse = True)]
s =0
for k,v in s_20:
    s += v
    print(k,":",v)
a_2 = s/len(s_20)  

Shoaib Akhtar : 2.27290608438
Muralitharan M : 1.42343444404
Grimmett C V : 1.41837402018
Steyn D W : 1.38785566114
Pollock S M : 1.29139322478
Tate M W : 1.27633242432
Hadlee R J : 1.25442346211
McGrath G D : 1.23079045711
Donald A A : 1.22232154255
Jadeja R A : 1.19590575165
Martin C S : 1.18814526131
Yasir Shah : 1.18493221204
Lock G A R : 1.18479306084
Ashwin R : 1.17959426762
Trueman F S : 1.16825478494
Imran Khan : 1.1621886761
Warne S K : 1.14783827992
Ambrose C E L : 1.1292206222
Garner J : 1.12687791292
Davidson A K : 1.11474341622
Philander V D : 1.11091962134
Miller K R : 1.09214249461
Gillespie J N : 1.08553428232
McKenzie G D : 1.08268324057
Waqar Younis : 1.07064452061
Laker J C : 1.06890018489
Streak H H : 1.06260144199
Johnson M G : 1.06153460482
Johnston W A : 1.05755194194
Kumble A : 1.05165537468
Marshall M D : 1.04397645113
Wasim Akram : 1.04217988645
Swann G P : 1.04171567653
MacGill S C G : 1.03945198004
Anderson J M : 1.03652241421
Tayfield H J : 1.0352636152
Bou

In [22]:
bowl1=np.zeros(len(df1.index))
for i in df1.index:
    bowl1[i] = (wtrps[series_code[i]] - weighted_runs_arr[i])/(tops[series_code[i]]-df1["Overs"][i])
    e_r = df1["E/R"][i]
    bowl1[i] = bowl1[i]/e_r
    if e_r == 0:
        bowl1[i] = 0
bowl1[:14]

C:\Users\Vasthav\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """


array([ 0.4262822 ,  0.43704554,  0.30747195,  0.49979416,  0.53401697,
        0.32036545,  0.72606601,  0.15330486,  0.50030487,  0.50912074,
        0.5150356 ,  0.98172483,  0.46773393,  0.49006155])

In [23]:
runs_metric_30 = []
player_dict_temp_30 = {}


for i in player_names:
    no_of_wickets1=0
    spf_sum1 = 0
    no_series1 = 0
    no_balls = 0
    for j in player_dict_temp_3[i]:
        spf_sum1 += bowl1[j]
        no_series1 += 1
        no_of_wickets1 += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 3000):  
    if(no_of_wickets1 > 150): 
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_30[i] = spf_sum1/no_series1
    
s_30 = [(k,player_dict_temp_30[k]) for k in sorted(player_dict_temp_30, key=player_dict_temp_30.get, reverse = True)]

s =0
for k,v in s_30:
    s += v
    print(k,":",v)
a_3 = s/len(s_30)

Tate M W : 1.27473180702
Tayfield H J : 1.14762090847
Johnston W A : 1.14243651599
Gibbs L R : 1.11930328951
Vettori D L : 1.10737561733
Jadeja R A : 1.08959450822
Titmus F J : 1.08779542831
Davidson A K : 1.05921858846
Saeed Ajmal : 1.04414781501
Muralitharan M : 1.02120419542
McGrath G D : 1.0156956773
Miller K R : 1.01292543842
Iqbal Qasim M : 1.00257828361
Benaud R : 0.998787303682
Ramadhin S : 0.996944982877
Pollock S M : 0.995518452967
Grimmett C V : 0.97632872462
Ambrose C E L : 0.976127850989
Saqlain Mushtaq : 0.975093921112
Sarfraz Nawaz : 0.968158698641
Warne S K : 0.964848855998
Bedser A V : 0.960818307098
Lock G A R : 0.956839819878
Sobers G S A : 0.956420607153
Underwood D L : 0.948376651362
Philander V D : 0.948241669614
Wasim Akram : 0.945088209784
Bedi B S : 0.94437263991
Herath H M R K B : 0.94325732226
Laker J C : 0.938127013096
Kaneria D : 0.934702726783
Kumble A : 0.930098754457
Panesar M S : 0.928772613286
Vaas W P U J C : 0.927198718383
McKenzie G D : 0.9235245246

In [24]:
bowl2=np.zeros(len(df1.index))
for i in df1.index:
    bowl2[i] = (tbps[series_code[i]] - balls[i])/(twps[series_code[i]]-df1["Wickets"][i])
    s_r = df1["S/R"][i]
    bowl2[i] = bowl2[i]/s_r
    if np.isnan(s_r) or s_r == 0:
        bowl2[i] = 0

In [25]:
runs_metric_40 = []
player_dict_temp_40 = {}


for i in player_names:
    no_of_wickets2=0
    spf_sum2 = 0
    no_series2 = 0
    no_balls = 0
    for j in player_dict_temp_3[i]:
        spf_sum2 += bowl2[j]
        no_series2 += 1
        no_of_wickets2 += df1["Wickets"][j]
        #no_balls += balls[j]
    #if(no_balls > 3000):
    if(no_of_wickets2 > 150):    
        #runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_40[i] = spf_sum2/no_series2
    
s_40 = [(k,player_dict_temp_40[k]) for k in sorted(player_dict_temp_40, key=player_dict_temp_40.get, reverse = True)]

s_1 =0
for k,v in s_40:
    s_1 += v
    print(k,":",v)
a_4 = s_1/len(s_40) 

Shoaib Akhtar : 1.75146510962
Steyn D W : 1.59689626842
Trueman F S : 1.51329701193
Donald A A : 1.41685031374
Hadlee R J : 1.34132794927
Hall W W : 1.32558965537
Grimmett C V : 1.32397024388
Waqar Younis : 1.3189361788
Marshall M D : 1.29236742673
MacGill S C G : 1.26907695316
Holding M A : 1.25432770204
Hughes M G : 1.24954430415
Imran Khan : 1.23794377067
Lee B : 1.23744225742
Johnson M G : 1.2366641246
Muralitharan M : 1.22646695674
Garner J : 1.2247709518
Willis R G D : 1.22028482332
Starc M A : 1.21482894465
Gough D : 1.20999438604
Ashwin R : 1.19610719505
Snow J A : 1.19386768361
Yasir Shah : 1.19217974925
Botham I T : 1.18497571217
Fraser A R C : 1.18308647545
Pollock S M : 1.18003452982
Cairns C L : 1.17878974671
Umar Gul : 1.17640982447
Martin C S : 1.17365033295
Lillee D K : 1.17117214094
Edwards F H : 1.16375336224
Laker J C : 1.16103861377
Srinath J : 1.14756522934
Morkel M : 1.14699543099
McGrath G D : 1.14687518687
Roberts A M E : 1.1456534961
Philander V D : 1.145326503

In [26]:
avg = [a_2, a_3, a_4]
w = np.average(avg)/avg
w

array([ 0.99018156,  1.11790622,  0.91277955])

In [27]:
player_dict_temp_50 = {}

for i in player_dict_temp_40.keys():
    player_dict_temp_50[i] = (w[0]*player_dict_temp_20[i]+w[1]*player_dict_temp_30[i]+w[2]*player_dict_temp_40[i])/np.sum(w)
    
s_50 = [(k,player_dict_temp_50[k]) for k in sorted(player_dict_temp_50, key=player_dict_temp_50.get, reverse = True)]

for k,v in s_50:
    print(k,":",v)

Shoaib Akhtar : 1.61429391804
Steyn D W : 1.24083251733
Grimmett C V : 1.22626527787
Muralitharan M : 1.21506925502
Tate M W : 1.18057354337
Pollock S M : 1.14825347687
Hadlee R J : 1.13537388181
Donald A A : 1.13195908922
McGrath G D : 1.1258365148
Trueman F S : 1.12128207924
Jadeja R A : 1.10012511389
Lock G A R : 1.08777000181
Imran Khan : 1.0853144081
Ashwin R : 1.07926874627
Yasir Shah : 1.07085699653
Garner J : 1.06669783811
Davidson A K : 1.06312589307
Ambrose C E L : 1.0625009465
Warne S K : 1.06234693115
Philander V D : 1.0611151182
Martin C S : 1.05535831444
Laker J C : 1.04834646217
Miller K R : 1.04580349079
Waqar Younis : 1.03499458805
McKenzie G D : 1.03280838098
Gillespie J N : 1.03275607521
Johnston W A : 1.03102303491
Marshall M D : 1.02822027204
Johnson M G : 1.0240366431
Tayfield H J : 1.02040442069
Hall W W : 1.01861415364
Kumble A : 1.01311258373
Wasim Akram : 1.01187822006
Swann G P : 1.00862706388
MacGill S C G : 1.0069150805
Anderson J M : 1.00575296215
Boult T 

In [32]:
for k,v in s_50:
    first = player_indices[np.where(player_names == k)[0][0]]
    #print(first,"->",df[' Decade_Index '][first])
    if df1['Decade_Index'][first] >= 6:
        print(k,":",v)

Shoaib Akhtar : 1.61429391804
Steyn D W : 1.24083251733
Muralitharan M : 1.21506925502
Pollock S M : 1.14825347687
Donald A A : 1.13195908922
McGrath G D : 1.1258365148
Jadeja R A : 1.10012511389
Ashwin R : 1.07926874627
Yasir Shah : 1.07085699653
Ambrose C E L : 1.0625009465
Warne S K : 1.06234693115
Philander V D : 1.0611151182
Martin C S : 1.05535831444
Waqar Younis : 1.03499458805
Gillespie J N : 1.03275607521
Johnson M G : 1.0240366431
Kumble A : 1.01311258373
Wasim Akram : 1.01187822006
Swann G P : 1.00862706388
MacGill S C G : 1.0069150805
Anderson J M : 1.00575296215
Boult T A : 1.00037900199
Streak H H : 0.996355892441
Morkel M : 0.987763322894
Saeed Ajmal : 0.987193060354
Saqlain Mushtaq : 0.98381869829
Herath H M R K B : 0.982943159232
Lee B : 0.982939784736
Harmison S J : 0.979719817635
Walsh C A : 0.977895481068
Hazlewood J R : 0.966250210152
Vettori D L : 0.965401925514
Southee T G : 0.959341170124
Vaas W P U J C : 0.956281383869
Fraser A R C : 0.950990049216
Hoggard M J 

In [28]:
trps


array([ 1277.,   449.,   871.,  2991.,   334.,  1801.,  2001.,  3319.,
        1761.,   886.,   343.,  1039.,   704.,   961.,  2466.,   447.,
        2142.,  4994.,  1536.,  2044.,  5079.,  1249.,  4229.,  4154.,
        2908.,  2419.,  4564.,  4359.,  3650.,  1680.,  5397.,  3221.,
        4357.,  5925.,  5103.,  3773.,  5809.,  3875.,  2823.,  4018.,
        3174.,  6271.,  3681.,  4439.,  2064.,  6420.,  4443.,  2513.,
        5110.,  5106.,  3705.,  4000.,  2043.,  3865.,  1817.,   841.,
        4886.,  1275.,  1898.,  2509.,  5140.,  2540.,  4330.,  4189.,
        2199.,  4721.,  2627.,  4216.,  5557.,  2500.,   156.,  1866.,
        5629.,   372.,  5596.,  3918.,  3855.,  5217.,  5446.,  4980.,
        4238.,  4299.,  4029.,  3889.,  1331.,  3876.,  4262.,  4351.,
        1381.,  2860.,  3313.,  5588.,  5020.,  1485.,  4122.,  3717.,
        5415.,  2239.,  4110.,  3331.,   879.,  6002.,  4382.,  2152.,
        4303.,  2540.,  3401.,   484.,  2050.,  3695.,  4398.,  4122.,
      

In [29]:
len(trps)

723