In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline




In [2]:
df = pd.read_csv("records_final_series_test_final_corrected_v1.csv")

In [3]:
df.head(6)

Player    Country % Team Runs  Mat  Inns  NO  50s  100s  0s    HS  \
0  Bannerman C  Australia      28.63%    2     4   1    0     1   0  165*   
1     Ulyett G    England      21.69%    2     4   0    2     0   0    63   
2       Hill A    England      14.70%    2     4   2    0     0   1    49   
3  Greenwood A    England      11.21%    2     4   0    0     0   0    49   
4     Emmett T    England      10.63%    2     4   0    0     0   0    48   
5       Jupp H    England       9.90%    2     4   0    1     0   1    63   

   Runs    S/R    Avg  Ca  St  Series_Code   H/A   Decade_Index   
0   209  -0.14  69.67   0   0            1  Home               0  
1   149  -0.15  37.25   2   0            1  Away               0  
2   101   -0.1   50.5   1   0            1  Away               0  
3    77  -0.08  19.25   2   0            1  Away               0  
4    73  -0.07  18.25   4   0            1  Away               0  
5    68  -0.07     17   2   0            1  Away               0

In [4]:
series = df[' Decade_Index '].values
print(series)


[ 0  0  0 ... 13 13 13]


In [5]:
print(df['Series_Code'][1000])

39


In [6]:
number, series_unique = np.unique(series, return_inverse = True)  
print(number)
print(len(series_unique))
print(len(number))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
19848
14


In [7]:
players = df['Player'].values
player_names, player_indices = np.unique(players, return_index = True)
print(player_names)
print(len(player_names))
print(len(player_indices))

["A'Beckett E L" 'Aamer Malik' 'Aamir Nazir' ... 'van Zyl S'
 'van der Bijl P G V' 'van der Merwe P L']
2876
2876


In [8]:
# -> filter the players based on decades 

player_dict_temp_3 = {}
for i in df.index:
    if df["Player"][i] in player_dict_temp_3.keys():
        player_dict_temp_3[df["Player"][i]] = player_dict_temp_3[df["Player"][i]] + [i]
    else:
        player_dict_temp_3[df["Player"][i]] = [i]



In [9]:
print(player_dict_temp_3['Aamer Malik'])

[8280, 8421, 8506, 8578, 8665, 8757, 8941, 9962]


In [10]:
# to do -> remove unnecessary dictionaries and instead use series_occurences that we defined later to find the first occurence of every series
trps = dict() #total runs per series
mps = {} # matches per series
arps = {} #average runs per series
sid = {} # series in decade
arpd = np.zeros(14)
tspd = np.zeros(14)
for i in df.index:
    x = df['Series_Code'][i]
    trps[x] = 0
    mps[x] = 0
    #arps[x] = 0
    
    
for i in df.index:
    x = df['Series_Code'][i]
    trps[x] = trps[x] + df['Runs'][i]
    mps[x] = max(mps[x],df['Mat'][i])
    sid[x] = df[' Decade_Index '][i]

for i in trps.keys():
    arps[i] =trps[i]/mps[i]
    
for i in arps.keys():
    arpd[sid[i]]+= arps[i]
    tspd[sid[i]] += 1          
    
arpd = arpd/tspd
w = np.sum(arpd)/arpd
w = w/np.average(w)
print(w)


#print(1,2)
#print(k)


#print(d[1] + d[2])
    

[1.37379319 1.02405175 0.99247044 1.06781918 0.94435217 0.97497954
 0.98728066 1.04158059 1.01021959 1.00640846 0.92513837 0.8725503
 0.88792006 0.8914357 ]


arps

In [11]:
total_entries = len(df.index)

In [12]:
weighted_runs = np.zeros(total_entries)
for i in df.index:
    #print(i)
    weighted_runs[i] = df["Runs"][i]*w[df[" Decade_Index "][i]]

In [13]:
weighted_runs

array([287.12277735, 204.69518576, 138.7531125 , ...,  16.04584257,
        14.26297118,   1.7828714 ])

In [15]:
runs_metric = []
player_dict_temp_4 = {}


for i in player_names:
    no_of_matches=0
    runs = 0
    for j in player_dict_temp_3[i]:
        runs += weighted_runs[j]
        no_of_matches += (df['Inns'][j] - df['NO'][j])
    if(no_of_matches > 40):    
        runs_metric.append(runs/no_of_matches)
        player_dict_temp_4[i] = (runs/no_of_matches)
    
print(player_dict_temp_4)

{'Aamir Sohail': 35.60701125335831, 'Abdul Qadir': 15.738413956424148, 'Abdul Razzaq': 25.46127552587996, 'Abid Ali S': 19.52593333810979, 'Adams J C': 41.60905571015221, 'Ali M M': 28.841502935755262, 'Alimuddin': 26.062001676121877, 'Amarnath M': 42.1523553844491, 'Ambrose C E L': 12.605800278718608, 'Ames L E G': 40.261217419515226, 'Amiss D L': 45.099970299175546, 'Amla H M': 42.37632019967529, 'Anderson J M': 8.688838559790852, 'Armstrong W W': 39.55486199611369, 'Arnold R P': 24.683703357543113, 'Arthurton K L T': 31.098141838767564, 'Asad Shafiq': 35.29209827952185, 'Ashwin R': 27.255667763514698, 'Asif Iqbal': 37.596139067877886, 'Astle N J': 35.76508375831779, 'Atapattu M S': 37.159628577496186, 'Atherton M A': 38.005948049516164, 'Azhar Ali': 41.38191243987351, 'Azharuddin M': 46.139094114840475, 'Bailey T E': 31.757219889958904, 'Bairstow J M': 34.896011017212786, 'Bannerman A C': 31.71172620596937, 'Barber R W': 33.64089758396076, 'Bardsley W': 38.288348387191355, 'Barlow E

In [16]:
runs_metric = []
player_dict_temp_5= {}


for i in player_names:
    no_of_matches=0
    runs = 0
    for j in player_dict_temp_3[i]:
        runs += weighted_runs[j]
        no_of_matches += (df['Inns'][j] - df['NO'][j])
    if(no_of_matches > 80):    
        runs_metric.append(runs/no_of_matches)
        player_dict_temp_5[i] = (runs/no_of_matches)
    
print(player_dict_temp_5)       

{'Amarnath M': 42.1523553844491, 'Ambrose C E L': 12.605800278718608, 'Amla H M': 42.37632019967529, 'Anderson J M': 8.688838559790852, 'Asad Shafiq': 35.29209827952185, 'Asif Iqbal': 37.596139067877886, 'Astle N J': 35.76508375831779, 'Atapattu M S': 37.159628577496186, 'Atherton M A': 38.005948049516164, 'Azhar Ali': 41.38191243987351, 'Azharuddin M': 46.139094114840475, 'Bairstow J M': 34.896011017212786, 'Barrington K F': 56.531396902729036, 'Bell I R': 37.77679308859733, 'Benaud R': 25.424067960985766, 'Boon D C': 44.54967727428131, 'Borde C G': 34.92741603563531, 'Border A R': 50.798571375632605, 'Botham I T': 33.262950031040475, 'Boucher M V': 28.174997451289443, 'Boycott G': 46.01908133101904, 'Bravo D M': 35.4965938089554, 'Broad S C J': 17.981280109231054, 'Burgess M G': 30.162400510831155, 'Butcher M A': 32.813102834651524, 'Caddick A R': 10.215717634297363, 'Cairns C L': 33.16404150250069, 'Campbell A D R': 26.878490490857804, 'Campbell S L': 32.591449640681, 'Chanderpaul S

In [69]:
s_4 = [(k,player_dict_temp_4[k]) for k in sorted(player_dict_temp_4, key=player_dict_temp_4.get, reverse = True)]
#print(s_4)
for k,v in s_4:
    print(k,":",v)

Bradman D G : 101.23874065853317
Weekes E D C : 62.59387454006006
Walcott C L : 60.53100389714477
Sutcliffe H : 60.27603791155031
Hutton L : 59.6944997414219
Hammond W R : 58.24190196387068
Hobbs J B : 58.23854627134505
Sobers G S A : 57.82277728325969
Barrington K F : 56.531396902729036
Nourse A D : 55.965221999974446
Smith S P D : 54.548593880061844
Compton D C S : 53.15140334975746
Javed Miandad : 52.68983346394979
Chappell G S : 52.623483023631096
Worrell F M M : 52.09306008011934
Lara B C : 51.30554587855926
Harvey R N : 50.988337339882015
Waugh S R : 50.93568517392522
Flower A : 50.894263299679366
Hazare V S : 50.883905467123824
Kallis J H : 50.86926493340105
Border A R : 50.798571375632605
Sangakkara K C : 50.62918083144018
Tendulkar S R : 50.565766645812104
Gavaskar S M : 50.354883317182654
Richards I V A : 50.07903908567881
Mitchell B : 49.65688373493321
Morris A R : 49.639541806965696
May P B H : 49.59909907772648
Hassett A L : 49.491120486546606
Mohammad Yousuf : 48.80739941

In [70]:
s_5 = [(k,player_dict_temp_5[k]) for k in sorted(player_dict_temp_5, key=player_dict_temp_5.get, reverse = True)]
#print(s_5)
for k,v in s_5:
    print(k,":",v)

Hutton L : 59.6944997414219
Hammond W R : 58.24190196387068
Hobbs J B : 58.23854627134505
Sobers G S A : 57.82277728325969
Barrington K F : 56.531396902729036
Smith S P D : 54.548593880061844
Compton D C S : 53.15140334975746
Javed Miandad : 52.68983346394979
Chappell G S : 52.623483023631096
Lara B C : 51.30554587855926
Harvey R N : 50.988337339882015
Waugh S R : 50.93568517392522
Flower A : 50.894263299679366
Kallis J H : 50.86926493340105
Border A R : 50.798571375632605
Sangakkara K C : 50.62918083144018
Tendulkar S R : 50.565766645812104
Gavaskar S M : 50.354883317182654
Richards I V A : 50.07903908567881
May P B H : 49.59909907772648
Mohammad Yousuf : 48.807399413576
Dravid R : 48.74665419289015
Ponting R T : 47.78106539388557
Kohli V : 47.504885049341894
Chanderpaul S : 47.36533556767746
Kanhai R B : 47.18459818709517
Inzamam-ul-Haq : 47.120554006227486
Younis Khan : 46.9340421017666
Root J E : 46.816977644310015
Dexter E R : 46.59051878561218
Walters K D : 46.35393561189102
Hayd

In [23]:
series_codes = df['Series_Code'].values
print(series_codes)

[  1   1   1 ... 735 735 735]


In [25]:
series_list, series_occurances = np.unique(series_codes, return_index=True)
#series_occurances

In [26]:
dict_series={}
for i in range(len(series_list)):
    dict_series[series_list[i]] = i

In [30]:
#series_list
#print(series_occurances)
series_to_number = {'Australia':0, 'Pakistan':1, 'New Zealand':2, 'West Indies':3, 'England':4, 'India' :5, 'Sri Lanka':6, 'Bangladesh':7, 'Zimbabwe':8, 'South Africa':9} 
opposition_country =[]
series_country = []
j = 0
for i in series_occurances:
    home = 0
    away = 0
    j = i
    while 1 != 0:
        #print(j)
        if df[' H/A'][j] == 'Home' and home == 0:
            #print(df['Country'][j])
            series_country.append(series_to_number[df['Country'][j]]) 
            home = home + 1
        elif df[' H/A'][j] == 'Away' and away == 0:    
            #print(df['Country'][j])
            opposition_country.append(series_to_number[df['Country'][j]]) 
            away = away + 1
        elif home == 1 and away == 1:
            #print("hello")
            break
        j = j + 1    
       
#print(series_country)
#print(opposition_country)

#print(len(series_country))
#print(len(opposition_country))
        

In [34]:
# filling up the 3D array (for countries/decade) -> first iteration
runs_per_country_decade = np.zeros((14,10,10))
series_per_country_decade = np.zeros((14,10,10))
for i in range(14):
    for j in range(len(series_occurances)):
        if df[' Decade_Index '][series_occurances[j]] == i:          
           # print(df['Series_Code'][series_occurances[j]])
            runs_per_country_decade[i][series_country[j]][opposition_country[j]] += arps[df['Series_Code'][series_occurances[j]]]
            series_per_country_decade[i][series_country[j]][opposition_country[j]] += 1

In [65]:
from numpy import inf
arpscd = runs_per_country_decade/series_per_country_decade
np.nan_to_num(arpscd, copy=False)
avg_arpscd = np.sum(arpscd)/arpscd
avg_arpscd[avg_arpscd == inf] = 0
avg_arpscd_around_1 = avg_arpscd/avg_arpscd[avg_arpscd.nonzero()].mean()

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
E:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [66]:
weighted_runs_1 = np.zeros(len(df.index))
for i in df.index:
    #print(i)
    index = dict_series[df['Series_Code'][i]]
    #print(series_country[index])
    #print(index)
    weighted_runs_1[i] = df["Runs"][i]*avg_arpscd_around_1[df[" Decade_Index "][i]][series_country[index]][opposition_country[index]]

In [67]:
runs_metric_10 = []
player_dict_temp_10 = {}


for i in player_names:
    no_of_matches=0
    runs = 0
    for j in player_dict_temp_3[i]:
        runs += weighted_runs_1[j]
        no_of_matches += (df['Inns'][j] - df['NO'][j])
    if(no_of_matches > 40):    
        runs_metric_10.append(runs/no_of_matches)
        player_dict_temp_10[i] = (runs/no_of_matches)
        
s_10 = [(k,player_dict_temp_10[k]) for k in sorted(player_dict_temp_10, key=player_dict_temp_10.get, reverse = True)]

for k,v in s_10:
    print(k,":",v)

Bradman D G : 96.96613705622279
Hutton L : 59.103284657624
Hammond W R : 58.18806059833507
Sutcliffe H : 57.23874872229986
Barrington K F : 56.27115959058015
Hobbs J B : 55.59026061397844
Nourse A D : 54.40469059771444
Compton D C S : 54.231830031390025
Smith S P D : 54.22064503079693
Javed Miandad : 53.22123757907448
Lara B C : 52.08469597960029
Flower A : 51.99128469573375
Weekes E D C : 51.881934386618795
Chappell G S : 51.20978648862176
Sangakkara K C : 50.66425011609017
Gavaskar S M : 50.596105055561324
Sobers G S A : 50.568926822605654
Kallis J H : 50.2360500813623
Richards I V A : 50.1924550578368
Mitchell B : 49.91227441697074
May P B H : 49.66300855021913
Chanderpaul S : 49.185852923573066
Hazare V S : 49.141174337230574
Border A R : 48.746807212379814
Waugh S R : 48.49266177780255
Hanif Mohammad : 48.436559428913924
Walcott C L : 48.274518411794894
Tendulkar S R : 48.235811832016715
Mohammad Yousuf : 47.82377188501924
Richardson R B : 47.79946730898553
Shoaib Mohammad : 47.74

In [35]:
# filling up the 3D array (for countries/decade) -> second iteration 
runs_per_country_decade1 = np.zeros((14,10,10))
series_per_country_decade1 = np.zeros((14,10,10))
for i in range(14):
    for j in range(len(series_occurances)):
        if df[' Decade_Index '][series_occurances[j]] == i:          
           # print(df['Series_Code'][series_occurances[j]])
            runs_per_country_decade1[i][series_country[j]][opposition_country[j]] += arps[df['Series_Code'][series_occurances[j]]]
            series_per_country_decade1[i][series_country[j]][opposition_country[j]] += 1

In [50]:
from numpy import inf
arpscd1 = runs_per_country_decade1/series_per_country_decade1
np.nan_to_num(arpscd1, copy=False)
l_6= np.true_divide(arpscd1.sum(1),(arpscd1!=0).sum(1))
np.nan_to_num(l_6, copy=False)
l_7 = np.true_divide(l_6.sum(1),(l_6!=0).sum(1))
k = l_7[:,None,None]/arpscd1
k[k == inf] = 0
k_20 = w[:,None,None] * k

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
E:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
E:\Anaconda\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


In [51]:
weighted_runs_2 = np.zeros(len(df.index))
for i in df.index:
    #print(i)
    index = dict_series[df['Series_Code'][i]]
    #print(series_country[index])
    #print(index)
    weighted_runs_2[i] = df["Runs"][i]*k_20[df[" Decade_Index "][i]][series_country[index]][opposition_country[index]]

In [52]:
runs_metric_20 = []
player_dict_temp_20 = {}


for i in player_names:
    no_of_matches=0
    runs = 0
    for j in player_dict_temp_3[i]:
        runs += weighted_runs_2[j]
        no_of_matches += (df['Inns'][j] - df['NO'][j])
    if(no_of_matches > 40):    
        runs_metric_20.append(runs/no_of_matches)
        player_dict_temp_20[i] = (runs/no_of_matches)
    
s_20 = [(k,player_dict_temp_20[k]) for k in sorted(player_dict_temp_20, key=player_dict_temp_20.get, reverse = True)]

for k,v in s_20:
    print(k,":",v)

Bradman D G : 93.2639088420652
Hutton L : 58.66336617583343
Barrington K F : 56.59827916921631
Hammond W R : 55.140947740182725
Compton D C S : 54.208575472517765
Sutcliffe H : 54.03070424800475
Hobbs J B : 53.4765496387238
Nourse A D : 53.439144318469154
Javed Miandad : 52.971030177428034
Smith S P D : 52.96629986207036
Weekes E D C : 52.109810826047976
Lara B C : 51.569162788201886
Chappell G S : 51.480315506787015
Flower A : 51.418267267177185
Sobers G S A : 50.894659471352334
Gavaskar S M : 50.67941815606433
Richards I V A : 50.09761677281031
May P B H : 49.88594350560584
Sangakkara K C : 49.85794716652889
Kallis J H : 49.60802907315119
Hazare V S : 49.35701277829349
Hanif Mohammad : 48.680660266270834
Walcott C L : 48.486550316558954
Chanderpaul S : 48.461143730150994
Border A R : 48.37995976770667
Amiss D L : 48.28227945538121
Mitchell B : 48.038871994023175
Waugh S R : 48.003569010192024
Sutcliffe B : 47.6716366566573
Tendulkar S R : 47.66017035886945
Richardson R B : 47.3399424

In [68]:
runs_metric_30 = []
player_dict_temp_30 = {}


for i in player_names:
    no_of_matches=0
    runs = 0
    for j in player_dict_temp_3[i]:
        runs += weighted_runs_2[j]
        no_of_matches += (df['Inns'][j] - df['NO'][j])
    if(no_of_matches > 35):    
        runs_metric_30.append(runs/no_of_matches)
        player_dict_temp_30[i] = (runs/no_of_matches)
    
#print(player_dict_temp_30)
s_30 = [(k,player_dict_temp_30[k]) for k in sorted(player_dict_temp_30, key=player_dict_temp_30.get, reverse = True)]

for k,v in s_30:
    print(k,":",v)
#print(s)

Bradman D G : 93.2639088420652
Headley G A : 59.7200159349337
Hutton L : 58.66336617583343
Barrington K F : 56.59827916921631
Hammond W R : 55.140947740182725
Compton D C S : 54.208575472517765
Sutcliffe H : 54.03070424800475
Hobbs J B : 53.4765496387238
Nourse A D : 53.439144318469154
Javed Miandad : 52.971030177428034
Smith S P D : 52.96629986207036
Pollock R G : 52.61525912206723
Weekes E D C : 52.109810826047976
Lara B C : 51.569162788201886
Chappell G S : 51.480315506787015
Flower A : 51.418267267177185
Sobers G S A : 50.894659471352334
Gavaskar S M : 50.67941815606433
Richards I V A : 50.09761677281031
May P B H : 49.88594350560584
Sangakkara K C : 49.85794716652889
Kallis J H : 49.60802907315119
Hazare V S : 49.35701277829349
Hanif Mohammad : 48.680660266270834
Walcott C L : 48.486550316558954
Chanderpaul S : 48.461143730150994
Border A R : 48.37995976770667
Amiss D L : 48.28227945538121
Mitchell B : 48.038871994023175
Waugh S R : 48.003569010192024
Sutcliffe B : 47.671636656657

In [ ]:
# filling up the 3D array (for countries/decade) -> first iteration
runs_per_country_decade3 = np.zeros((14,10,10))
matches_per_country_decade3 = np.zeros((14,10,10))
series = []
for i in df.index:
    index = dict_series[df['Series_Code'][i]]
    runs_per_country_decade3[df[" Decade_Index "][i]][series_country[index]][df["Country"][i]] += df["Runs"][i]
    if df['Series_Code'][i] not in series:
        series.append(df['Series_Code'][i])
        matches_per_country_decade3["Decade"] = 